[package]
name = "TNTTagBruteforce"
version = "0.1.0"
edition = "2021"

[profile.release]
lto = "fat"
codegen-units = 1
panic = "abort"

[build]
rustflags = ["-C", "target-cpu=native"]

[dependencies]
lazy_static = "1.4.0"
rayon = "1.10.0"
atomic-counter = "1.0.1"